import clearingHouseAbi from "./ClearingHouse.json";
import chainLinkAbi from "./ChainlinkPriceFeed.json";
import erc20Abi from "./ERC20.json";
import bridgeAbi from "./Bridge.json";
import ammAbi from "./AMM.json";
export const clearingHouseABI = clearingHouseAbi;
export const chainLinkABI = chainLinkAbi;
export const erc20ABI = erc20Abi;
export const bridgeABI = bridgeAbi;
export const ammABI = ammAbi;
